version: '3.8'

services:

  app:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - 5000:5000
    env_file: 
      - .env
    depends_on: 
      - db


  db:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
    restart: always

  db-test:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
    volumes:
        - ./postgres-test/data:/var/lib/postgresql/data
    restart: always

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:8080
  #   depends_on:
  #     - app
  #     - db
