version: '3.8'

services:

  app:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "127.0.0.1:5000:5000"
    env_file: 
      - .env
    command: flask run --cert=adhoc
    depends_on: 
      - db

  celery_worker:
    build: ./client
    volumes:
      - ./client:/app
    env_file:
      - .env
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis

  celery_flower:
    build: ./client
    volumes:
      - ./client:/app
    env_file:
      - .env
    ports:
      - "127.0.0.1:5555:5555"
    command: celery -A app.celery flower --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis


  redis:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:6379:6379"
      
  db:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
    restart: always


  db-test:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
    volumes:
        - ./postgres-test/data:/var/lib/postgresql/data
    restart: always




  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:8080
  #   depends_on:
  #     - app
  #     - db

